Added commands to how to use section
mkusher/padawan.php pull request #74
Opened 2016-12-22 13:03 UTC by kokx

It is relately hard to figure out which commands to run to index a project directory, and how to run the server.

This PR adds these commands to the How To Use section in the README, to make it easier for new users.

2016-12-22 13:08 UTC, mkusher requested changes

2016-12-22 13:08 UTC, mkusher commented on README.md
> +padawan generate index
index is unnecessary here

2016-12-27 11:44 UTC, kokx commented on README.md
> +padawan generate index
Fixed! Didn't know that I didn't need that.

2016-12-27 11:48 UTC, mkusher approved these changes

2016-12-27 11:48 UTC, merged

2016-12-27 11:49 UTC, mkusher commented
thx!